DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS film_genres CASCADE;
DROP TABLE IF EXISTS rating CASCADE;

CREATE TABLE IF NOT EXISTS users (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50),
login varchar(50) NOT NULL,
email varchar(100) NOT NULL,
birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS friends (
user_id integer NOT NULL REFERENCES users(id),
friend_id integer NOT NULL REFERENCES users(id),
friendship boolean
);

CREATE TABLE IF NOT EXISTS rating (
rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50) NOT NULL,
description varchar(200) NOT NULL,
release_date date NOT NULL,
duration integer NOT NULL,
rating_id integer NOT NULL REFERENCES rating (rating_id) 
);

CREATE TABLE IF NOT EXISTS likes (
film_id integer NOT NULL REFERENCES films(id),
user_id integer NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS film_genres (
film_id integer NOT NULL REFERENCES films(id),
genre_id integer NOT NULL REFERENCES genres(genre_id)
);
